import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

import { QueryProviders } from "@/provider/query-provider";
import { SheetProvider } from "@/provider/sheetProvider/sheet_provider";

import { clerkMiddleware } from "@clerk/nextjs/server";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'





const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <QueryProviders >
            <SheetProvider />
            <Toaster />
            {children}    
          </QueryProviders>
        </body>
      </html>
    </ClerkProvider>
  )
}